//
// Autogenerated by Natalie - Storyboard Generator Script.
// http://blog.krzyzanowskim.com
//

import UIKit

//MARK: - Storyboards

extension UIStoryboard {
    func instantiateViewController<T: UIViewController where T: IdentifiableProtocol>(type: T.Type) -> T? {
        let instance = type.init()
        if let identifier = instance.identifier {
            return self.instantiateViewControllerWithIdentifier(identifier) as? T
        }
        return nil
    }
}

protocol Storyboard {
    static var storyboard: UIStoryboard { get }
    static var identifier: String { get }
}

struct Storyboards {

    struct Main: Storyboard {

        static let identifier = "Main"

        static var storyboard: UIStoryboard {
            return UIStoryboard(name: self.identifier, bundle: nil)
        }

        static func instantiateInitialViewController() -> SidebarViewController {
            return self.storyboard.instantiateInitialViewController() as! SidebarViewController
        }

        static func instantiateViewControllerWithIdentifier(identifier: String) -> UIViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier(identifier)
        }

        static func instantiateViewController<T: UIViewController where T: IdentifiableProtocol>(type: T.Type) -> T? {
            return self.storyboard.instantiateViewController(type)
        }

        static func instantiateMainMenuViewController() -> MainMenuViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("MainMenuViewController") as! MainMenuViewController
        }

        static func instantiateMapNavigationController() -> UINavigationController {
            return self.storyboard.instantiateViewControllerWithIdentifier("MapNavigationController") as! UINavigationController
        }

        static func instantiateMessagingNavigationController() -> UINavigationController {
            return self.storyboard.instantiateViewControllerWithIdentifier("MessagingNavigationController") as! UINavigationController
        }

        static func instantiateFiltersNavigationController() -> UINavigationController {
            return self.storyboard.instantiateViewControllerWithIdentifier("FiltersNavigationController") as! UINavigationController
        }

        static func instantiateCreateConversationContainerViewController() -> CreateConversationContainerViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("CreateConversationContainerViewController") as! CreateConversationContainerViewController
        }

        static func instantiateBrowseCommunityViewController() -> BrowseCommunityViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("BrowseCommunityViewController") as! BrowseCommunityViewController
        }

        static func instantiateBrowseVolunteerViewController() -> BrowseVolunteerViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("BrowseVolunteerViewController") as! BrowseVolunteerViewController
        }

        static func instantiateSearchViewController() -> SearchViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("SearchViewController") as! SearchViewController
        }

        static func instantiateBrowseMapViewController() -> BrowseMapViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("BrowseMapViewController") as! BrowseMapViewController
        }

        static func instantiateTrainingDetailsViewControllerId() -> TrainingDetailsViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("TrainingDetailsViewControllerId") as! TrainingDetailsViewController
        }

        static func instantiateBrowseGridViewController() -> BrowseGridViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("BrowseGridViewController") as! BrowseGridViewController
        }

        static func instantiateExploreViewControllerId() -> ExploreViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("ExploreViewControllerId") as! ExploreViewController
        }

        static func instantiateBrowseListViewController() -> BrowseListViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("BrowseListViewController") as! BrowseListViewController
        }

        static func instantiateProductDetailsViewControllerId() -> ProductDetailsViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("ProductDetailsViewControllerId") as! ProductDetailsViewController
        }

        static func instantiateEmergencyDetailsControllerId() -> EmergencyDetailsController {
            return self.storyboard.instantiateViewControllerWithIdentifier("EmergencyDetailsControllerId") as! EmergencyDetailsController
        }

        static func instantiateVolunteerDetailsViewControllerId() -> VolunteerDetailsViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("VolunteerDetailsViewControllerId") as! VolunteerDetailsViewController
        }

        static func instantiateGiveBloodDetailsViewControllerId() -> GiveBloodDetailsViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("GiveBloodDetailsViewControllerId") as! GiveBloodDetailsViewController
        }

        static func instantiateMarketDetailsViewControllerId() -> MarketDetailsViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("MarketDetailsViewControllerId") as! MarketDetailsViewController
        }

        static func instantiateBomaHotelsDetailsViewControllerId() -> BomaHotelsDetailsViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("BomaHotelsDetailsViewControllerId") as! BomaHotelsDetailsViewController
        }

        static func instantiateEventDetailsViewControllerId() -> EventDetailsViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("EventDetailsViewControllerId") as! EventDetailsViewController
        }

        static func instantiatePromotionDetailsViewControllerId() -> PromotionDetailsViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("PromotionDetailsViewControllerId") as! PromotionDetailsViewController
        }

        static func instantiatePostViewController() -> PostViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("PostViewController") as! PostViewController
        }

        static func instantiateMapViewController() -> BrowseViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("MapViewController") as! BrowseViewController
        }

        static func instantiateBrowseCommunityNavigationController() -> UINavigationController {
            return self.storyboard.instantiateViewControllerWithIdentifier("BrowseCommunityNavigationController") as! UINavigationController
        }

        static func instantiateSettingsNavigationController() -> UINavigationController {
            return self.storyboard.instantiateViewControllerWithIdentifier("SettingsNavigationController") as! UINavigationController
        }

        static func instantiatePeopleNavigationController() -> UINavigationController {
            return self.storyboard.instantiateViewControllerWithIdentifier("PeopleNavigationController") as! UINavigationController
        }

        static func instantiatePeopleViewController() -> PeopleViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("PeopleViewController") as! PeopleViewController
        }

        static func instantiateUserProfileViewController() -> UserProfileViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("UserProfileViewController") as! UserProfileViewController
        }

        static func instantiateMyProfileNavigationController() -> UINavigationController {
            return self.storyboard.instantiateViewControllerWithIdentifier("MyProfileNavigationController") as! UINavigationController
        }

        static func instantiateCommunityFeedViewController() -> CommunityFeedViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("CommunityFeedViewController") as! CommunityFeedViewController
        }

        static func instantiateChangePasswordController() -> ChangePasswordViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("ChangePasswordController") as! ChangePasswordViewController
        }

        static func instantiateSettingsViewController() -> SettingsViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("SettingsViewController") as! SettingsViewController
        }

        static func instantiateCommunityViewController() -> CommunityViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("CommunityViewController") as! CommunityViewController
        }

        static func instantiateCommunityNavigationController() -> UINavigationController {
            return self.storyboard.instantiateViewControllerWithIdentifier("CommunityNavigationController") as! UINavigationController
        }

        static func instantiateWalletNavigationController() -> UINavigationController {
            return self.storyboard.instantiateViewControllerWithIdentifier("WalletNavigationController") as! UINavigationController
        }

        static func instantiateSplashViewController() -> UIViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("SplashViewController") as! UIViewController
        }

        static func instantiateWalletViewController() -> WalletViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("WalletViewController") as! WalletViewController
        }

        static func instantiateCreateCommunityConversationViewController() -> CreateCommunityConversationViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("CreateCommunityConversationViewController") as! CreateCommunityConversationViewController
        }

        static func instantiateCreateUserConversationViewController() -> CreateUserConversationViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("CreateUserConversationViewController") as! CreateUserConversationViewController
        }
    }

    struct Login: Storyboard {

        static let identifier = "Login"

        static var storyboard: UIStoryboard {
            return UIStoryboard(name: self.identifier, bundle: nil)
        }

        static func instantiateInitialViewController() -> UINavigationController {
            return self.storyboard.instantiateInitialViewController() as! UINavigationController
        }

        static func instantiateViewControllerWithIdentifier(identifier: String) -> UIViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier(identifier)
        }

        static func instantiateViewController<T: UIViewController where T: IdentifiableProtocol>(type: T.Type) -> T? {
            return self.storyboard.instantiateViewController(type)
        }

        static func instantiateLoginSignUpViewController() -> LoginSignupViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("LoginSignUpViewController") as! LoginSignupViewController
        }

        static func instantiateRegisterViewController() -> RegisterViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("RegisterViewController") as! RegisterViewController
        }

        static func instantiateRecoverPasswordViewController() -> RecoverPasswordViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("RecoverPasswordViewController") as! RecoverPasswordViewController
        }

        static func instantiateLoginViewController() -> LoginViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("LoginViewController") as! LoginViewController
        }

        static func instantiateRegisterInfoViewController() -> RegisterInfoViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("RegisterInfoViewController") as! RegisterInfoViewController
        }
    }

    struct NewItems: Storyboard {

        static let identifier = "NewItems"

        static var storyboard: UIStoryboard {
            return UIStoryboard(name: self.identifier, bundle: nil)
        }

        static func instantiateViewControllerWithIdentifier(identifier: String) -> UIViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier(identifier)
        }

        static func instantiateViewController<T: UIViewController where T: IdentifiableProtocol>(type: T.Type) -> T? {
            return self.storyboard.instantiateViewController(type)
        }

        static func instantiateAddProductViewController() -> AddProductViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("AddProductViewController") as! AddProductViewController
        }

        static func instantiateAddPostViewController() -> AddPostViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("AddPostViewController") as! AddPostViewController
        }

        static func instantiateAddCommunityViewController() -> AddCommunityViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("AddCommunityViewController") as! AddCommunityViewController
        }

        static func instantiateEditCommunityViewController() -> EditCommunityViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("EditCommunityViewController") as! EditCommunityViewController
        }

        static func instantiateEditProfileViewController() -> EditProfileViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("EditProfileViewController") as! EditProfileViewController
        }

        static func instantiatePostToContainerViewControllerId() -> PostToContainerViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("PostToContainerViewControllerId") as! PostToContainerViewController
        }

        static func instantiateAddPromotionViewController() -> AddPromotionViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("AddPromotionViewController") as! AddPromotionViewController
        }

        static func instantiateAddEventViewController() -> AddEventViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("AddEventViewController") as! AddEventViewController
        }
    }

    struct Onboarding: Storyboard {

        static let identifier = "Onboarding"

        static var storyboard: UIStoryboard {
            return UIStoryboard(name: self.identifier, bundle: nil)
        }

        static func instantiateInitialViewController() -> OnboardingNavigationController {
            return self.storyboard.instantiateInitialViewController() as! OnboardingNavigationController
        }

        static func instantiateViewControllerWithIdentifier(identifier: String) -> UIViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier(identifier)
        }

        static func instantiateViewController<T: UIViewController where T: IdentifiableProtocol>(type: T.Type) -> T? {
            return self.storyboard.instantiateViewController(type)
        }

        static func instantiatePhoneVerificationController() -> PhoneVerificationViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("PhoneVerificationController") as! PhoneVerificationViewController
        }

        static func instantiateMembershipPlansViewController() -> MembershipPlansViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("MembershipPlansViewController") as! MembershipPlansViewController
        }

        static func instantiatePlansViewController() -> PlansViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("PlansViewController") as! PlansViewController
        }

        static func instantiateSelectMembershipPlansViewController() -> SelectMembershipPlansViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("SelectMembershipPlansViewController") as! SelectMembershipPlansViewController
        }

        static func instantiatePhoneNumberNavigationController() -> OnboardingNavigationController {
            return self.storyboard.instantiateViewControllerWithIdentifier("PhoneNumberNavigationController") as! OnboardingNavigationController
        }

        static func instantiateCallAmbulanceViewController() -> CallAmbulanceViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("CallAmbulanceViewController") as! CallAmbulanceViewController
        }

        static func instantiateAmbulanceSentViewControllerId() -> AmbulanceSentViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("AmbulanceSentViewControllerId") as! AmbulanceSentViewController
        }

        static func instantiateDonateViewController() -> DonateViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("DonateViewController") as! DonateViewController
        }

        static func instantiateSelectPaymentMethodController() -> SelectPaymentMethodController {
            return self.storyboard.instantiateViewControllerWithIdentifier("SelectPaymentMethodController") as! SelectPaymentMethodController
        }

        static func instantiatePaymentViewControllerId() -> PaymentViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("PaymentViewControllerId") as! PaymentViewController
        }

        static func instantiateBraintreePaymentViewController() -> BraintreePaymentViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("BraintreePaymentViewController") as! BraintreePaymentViewController
        }

        static func instantiateDonateNotificationViewController() -> DonateNotificationViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("DonateNotificationViewController") as! DonateNotificationViewController
        }

        static func instantiateAmbulanceRequestedViewControllerId() -> AmbulanceRequestedViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("AmbulanceRequestedViewControllerId") as! AmbulanceRequestedViewController
        }

        static func instantiatePaymentCompletedViewController() -> PaymentCompletedViewController {
            return self.storyboard.instantiateViewControllerWithIdentifier("PaymentCompletedViewController") as! PaymentCompletedViewController
        }
    }
}

//MARK: - ReusableKind
enum ReusableKind: String, CustomStringConvertible {
    case TableViewCell = "tableViewCell"
    case CollectionViewCell = "collectionViewCell"

    var description: String { return self.rawValue }
}

//MARK: - SegueKind
enum SegueKind: String, CustomStringConvertible {    
    case Relationship = "relationship" 
    case Show = "show"                 
    case Presentation = "presentation" 
    case Embed = "embed"               
    case Unwind = "unwind"             
    case Push = "push"                 
    case Modal = "modal"               
    case Popover = "popover"           
    case Replace = "replace"           
    case Custom = "custom"             

    var description: String { return self.rawValue } 
}

//MARK: - SegueProtocol
public protocol IdentifiableProtocol: Equatable {
    var identifier: String? { get }
}

public protocol SegueProtocol: IdentifiableProtocol {
}

public func ==<T: SegueProtocol, U: SegueProtocol>(lhs: T, rhs: U) -> Bool {
    return lhs.identifier == rhs.identifier
}

public func ~=<T: SegueProtocol, U: SegueProtocol>(lhs: T, rhs: U) -> Bool {
    return lhs.identifier == rhs.identifier
}

public func ==<T: SegueProtocol>(lhs: T, rhs: String) -> Bool {
    return lhs.identifier == rhs
}

public func ~=<T: SegueProtocol>(lhs: T, rhs: String) -> Bool {
    return lhs.identifier == rhs
}

public func ==<T: SegueProtocol>(lhs: String, rhs: T) -> Bool {
    return lhs == rhs.identifier
}

public func ~=<T: SegueProtocol>(lhs: String, rhs: T) -> Bool {
    return lhs == rhs.identifier
}

//MARK: - ReusableViewProtocol
public protocol ReusableViewProtocol: IdentifiableProtocol {
    var viewType: UIView.Type? { get }
}

public func ==<T: ReusableViewProtocol, U: ReusableViewProtocol>(lhs: T, rhs: U) -> Bool {
    return lhs.identifier == rhs.identifier
}

//MARK: - Protocol Implementation
extension UIStoryboardSegue: SegueProtocol {
}

extension UICollectionReusableView: ReusableViewProtocol {
    public var viewType: UIView.Type? { return self.dynamicType }
    public var identifier: String? { return self.reuseIdentifier }
}

extension UITableViewCell: ReusableViewProtocol {
    public var viewType: UIView.Type? { return self.dynamicType }
    public var identifier: String? { return self.reuseIdentifier }
}

//MARK: - UIViewController extension
extension UIViewController {
    func performSegue<T: SegueProtocol>(segue: T, sender: AnyObject?) {
        if let identifier = segue.identifier {
            performSegueWithIdentifier(identifier, sender: sender)
        }
    }

    func performSegue<T: SegueProtocol>(segue: T) {
        performSegue(segue, sender: nil)
    }
}

//MARK: - UICollectionView

extension UICollectionView {

    func dequeueReusableCell<T: ReusableViewProtocol>(reusable: T, forIndexPath: NSIndexPath!) -> UICollectionViewCell? {
        if let identifier = reusable.identifier {
            return dequeueReusableCellWithReuseIdentifier(identifier, forIndexPath: forIndexPath)
        }
        return nil
    }

    func registerReusableCell<T: ReusableViewProtocol>(reusable: T) {
        if let type = reusable.viewType, identifier = reusable.identifier {
            registerClass(type, forCellWithReuseIdentifier: identifier)
        }
    }

    func dequeueReusableSupplementaryViewOfKind<T: ReusableViewProtocol>(elementKind: String, withReusable reusable: T, forIndexPath: NSIndexPath!) -> UICollectionReusableView? {
        if let identifier = reusable.identifier {
            return dequeueReusableSupplementaryViewOfKind(elementKind, withReuseIdentifier: identifier, forIndexPath: forIndexPath)
        }
        return nil
    }

    func registerReusable<T: ReusableViewProtocol>(reusable: T, forSupplementaryViewOfKind elementKind: String) {
        if let type = reusable.viewType, identifier = reusable.identifier {
            registerClass(type, forSupplementaryViewOfKind: elementKind, withReuseIdentifier: identifier)
        }
    }
}
//MARK: - UITableView

extension UITableView {

    func dequeueReusableCell<T: ReusableViewProtocol>(reusable: T, forIndexPath: NSIndexPath!) -> UITableViewCell? {
        if let identifier = reusable.identifier {
            return dequeueReusableCellWithIdentifier(identifier, forIndexPath: forIndexPath)
        }
        return nil
    }

    func registerReusableCell<T: ReusableViewProtocol>(reusable: T) {
        if let type = reusable.viewType, identifier = reusable.identifier {
            registerClass(type, forCellReuseIdentifier: identifier)
        }
    }

    func dequeueReusableHeaderFooter<T: ReusableViewProtocol>(reusable: T) -> UITableViewHeaderFooterView? {
        if let identifier = reusable.identifier {
            return dequeueReusableHeaderFooterViewWithIdentifier(identifier)
        }
        return nil
    }

    func registerReusableHeaderFooter<T: ReusableViewProtocol>(reusable: T) {
        if let type = reusable.viewType, identifier = reusable.identifier {
             registerClass(type, forHeaderFooterViewReuseIdentifier: identifier)
        }
    }
}


//MARK: - MainMenuViewController
extension MainMenuViewController: IdentifiableProtocol { 
    var identifier: String? { return "MainMenuViewController" }
    static var identifier: String? { return "MainMenuViewController" }
}


//MARK: - SidebarViewController
extension UIStoryboardSegue {
    func selection() -> SidebarViewController.Segue? {
        if let identifier = self.identifier {
            return SidebarViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension SidebarViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case DrawerSegue = "DrawerSegue"
        case ShowGridBrowse = "ShowGridBrowse"
        case ShowMessagesList = "ShowMessagesList"
        case ShowFilters = "ShowFilters"
        case ShowCommunities = "ShowCommunities"
        case ShowSettings = "ShowSettings"
        case ShowMyProfile = "ShowMyProfile"
        case ShowPeople = "ShowPeople"
        case ShowWallet = "ShowWallet"
        case ShowSplash = "ShowSplash"
        case ShowBrowse = "ShowBrowse"
        case ShowVolunteers = "ShowVolunteers"

        var kind: SegueKind? {
            switch (self) {
            case DrawerSegue:
                return SegueKind(rawValue: "custom")
            case ShowGridBrowse:
                return SegueKind(rawValue: "custom")
            case ShowMessagesList:
                return SegueKind(rawValue: "custom")
            case ShowFilters:
                return SegueKind(rawValue: "presentation")
            case ShowCommunities:
                return SegueKind(rawValue: "custom")
            case ShowSettings:
                return SegueKind(rawValue: "custom")
            case ShowMyProfile:
                return SegueKind(rawValue: "custom")
            case ShowPeople:
                return SegueKind(rawValue: "custom")
            case ShowWallet:
                return SegueKind(rawValue: "custom")
            case ShowSplash:
                return SegueKind(rawValue: "custom")
            case ShowBrowse:
                return SegueKind(rawValue: "custom")
            case ShowVolunteers:
                return SegueKind(rawValue: "custom")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case DrawerSegue:
                return MainMenuViewController.self
            case ShowGridBrowse:
                return UINavigationController.self
            case ShowMessagesList:
                return UINavigationController.self
            case ShowFilters:
                return UINavigationController.self
            case ShowCommunities:
                return UINavigationController.self
            case ShowSettings:
                return UINavigationController.self
            case ShowMyProfile:
                return UINavigationController.self
            case ShowPeople:
                return UINavigationController.self
            case ShowWallet:
                return UINavigationController.self
            case ShowSplash:
                return UIViewController.self
            case ShowBrowse:
                return UINavigationController.self
            case ShowVolunteers:
                return UINavigationController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - MessagesListViewController

//MARK: - CreateConversationContainerViewController
extension CreateConversationContainerViewController: IdentifiableProtocol { 
    var identifier: String? { return "CreateConversationContainerViewController" }
    static var identifier: String? { return "CreateConversationContainerViewController" }
}


//MARK: - FilterViewController

//MARK: - BrowseCommunityViewController
extension BrowseCommunityViewController: IdentifiableProtocol { 
    var identifier: String? { return "BrowseCommunityViewController" }
    static var identifier: String? { return "BrowseCommunityViewController" }
}

//MARK: - SearchViewController
extension SearchViewController: IdentifiableProtocol { 
    var identifier: String? { return "SearchViewController" }
    static var identifier: String? { return "SearchViewController" }
}


//MARK: - BrowseMapViewController
extension BrowseMapViewController: IdentifiableProtocol { 
    var identifier: String? { return "BrowseMapViewController" }
    static var identifier: String? { return "BrowseMapViewController" }
}


//MARK: - TrainingDetailsViewController
extension TrainingDetailsViewController: IdentifiableProtocol { 
    var identifier: String? { return "TrainingDetailsViewControllerId" }
    static var identifier: String? { return "TrainingDetailsViewControllerId" }
}


//MARK: - BrowseGridViewController
extension BrowseGridViewController: IdentifiableProtocol { 
    var identifier: String? { return "BrowseGridViewController" }
    static var identifier: String? { return "BrowseGridViewController" }
}


//MARK: - ExploreViewController
extension ExploreViewController: IdentifiableProtocol { 
    var identifier: String? { return "ExploreViewControllerId" }
    static var identifier: String? { return "ExploreViewControllerId" }
}


//MARK: - BrowseListViewController
extension BrowseListViewController: IdentifiableProtocol { 
    var identifier: String? { return "BrowseListViewController" }
    static var identifier: String? { return "BrowseListViewController" }
}


//MARK: - OrderViewController

//MARK: - ProductDetailsViewController
extension UIStoryboardSegue {
    func selection() -> ProductDetailsViewController.Segue? {
        if let identifier = self.identifier {
            return ProductDetailsViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension ProductDetailsViewController: IdentifiableProtocol { 
    var identifier: String? { return "ProductDetailsViewControllerId" }
    static var identifier: String? { return "ProductDetailsViewControllerId" }
}

extension ProductDetailsViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case ShowProductInventory = "ShowProductInventory"
        case ShowBuyScreen = "ShowBuyScreen"
        case ShowSellerProfile = "ShowSellerProfile"

        var kind: SegueKind? {
            switch (self) {
            case ShowProductInventory:
                return SegueKind(rawValue: "show")
            case ShowBuyScreen:
                return SegueKind(rawValue: "show")
            case ShowSellerProfile:
                return SegueKind(rawValue: "show")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case ShowProductInventory:
                return ProductInventoryViewController.self
            case ShowBuyScreen:
                return OrderViewController.self
            case ShowSellerProfile:
                return UserProfileViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - EmergencyDetailsController
extension UIStoryboardSegue {
    func selection() -> EmergencyDetailsController.Segue? {
        if let identifier = self.identifier {
            return EmergencyDetailsController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension EmergencyDetailsController: IdentifiableProtocol { 
    var identifier: String? { return "EmergencyDetailsControllerId" }
    static var identifier: String? { return "EmergencyDetailsControllerId" }
}

extension EmergencyDetailsController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case ShowSellerProfile = "ShowSellerProfile"
        case Donate = "Donate"

        var kind: SegueKind? {
            switch (self) {
            case ShowSellerProfile:
                return SegueKind(rawValue: "show")
            case Donate:
                return SegueKind(rawValue: "show")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case ShowSellerProfile:
                return UserProfileViewController.self
            case Donate:
                return OrderViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - VolunteerDetailsViewController
extension UIStoryboardSegue {
    func selection() -> VolunteerDetailsViewController.Segue? {
        if let identifier = self.identifier {
            return VolunteerDetailsViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension VolunteerDetailsViewController: IdentifiableProtocol { 
    var identifier: String? { return "VolunteerDetailsViewControllerId" }
    static var identifier: String? { return "VolunteerDetailsViewControllerId" }
}

extension VolunteerDetailsViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case ShowOrganizerProfile = "ShowOrganizerProfile"

        var kind: SegueKind? {
            switch (self) {
            case ShowOrganizerProfile:
                return SegueKind(rawValue: "show")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case ShowOrganizerProfile:
                return UserProfileViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - GiveBloodDetailsViewController
extension UIStoryboardSegue {
    func selection() -> GiveBloodDetailsViewController.Segue? {
        if let identifier = self.identifier {
            return GiveBloodDetailsViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension GiveBloodDetailsViewController: IdentifiableProtocol { 
    var identifier: String? { return "GiveBloodDetailsViewControllerId" }
    static var identifier: String? { return "GiveBloodDetailsViewControllerId" }
}

extension GiveBloodDetailsViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case ShowOrganizerProfile = "ShowOrganizerProfile"

        var kind: SegueKind? {
            switch (self) {
            case ShowOrganizerProfile:
                return SegueKind(rawValue: "show")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case ShowOrganizerProfile:
                return UserProfileViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - MarketDetailsViewController
extension UIStoryboardSegue {
    func selection() -> MarketDetailsViewController.Segue? {
        if let identifier = self.identifier {
            return MarketDetailsViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension MarketDetailsViewController: IdentifiableProtocol { 
    var identifier: String? { return "MarketDetailsViewControllerId" }
    static var identifier: String? { return "MarketDetailsViewControllerId" }
}

extension MarketDetailsViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case ShowOrganizerProfile = "ShowOrganizerProfile"

        var kind: SegueKind? {
            switch (self) {
            case ShowOrganizerProfile:
                return SegueKind(rawValue: "show")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case ShowOrganizerProfile:
                return UserProfileViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - BomaHotelsDetailsViewController
extension UIStoryboardSegue {
    func selection() -> BomaHotelsDetailsViewController.Segue? {
        if let identifier = self.identifier {
            return BomaHotelsDetailsViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension BomaHotelsDetailsViewController: IdentifiableProtocol { 
    var identifier: String? { return "BomaHotelsDetailsViewControllerId" }
    static var identifier: String? { return "BomaHotelsDetailsViewControllerId" }
}

extension BomaHotelsDetailsViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case ShowOrganizerProfile = "ShowOrganizerProfile"

        var kind: SegueKind? {
            switch (self) {
            case ShowOrganizerProfile:
                return SegueKind(rawValue: "show")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case ShowOrganizerProfile:
                return UserProfileViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - EventDetailsViewController
extension UIStoryboardSegue {
    func selection() -> EventDetailsViewController.Segue? {
        if let identifier = self.identifier {
            return EventDetailsViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension EventDetailsViewController: IdentifiableProtocol { 
    var identifier: String? { return "EventDetailsViewControllerId" }
    static var identifier: String? { return "EventDetailsViewControllerId" }
}

extension EventDetailsViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case ShowOrganizerProfile = "ShowOrganizerProfile"

        var kind: SegueKind? {
            switch (self) {
            case ShowOrganizerProfile:
                return SegueKind(rawValue: "show")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case ShowOrganizerProfile:
                return UserProfileViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - PromotionDetailsViewController
extension UIStoryboardSegue {
    func selection() -> PromotionDetailsViewController.Segue? {
        if let identifier = self.identifier {
            return PromotionDetailsViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension PromotionDetailsViewController: IdentifiableProtocol { 
    var identifier: String? { return "PromotionDetailsViewControllerId" }
    static var identifier: String? { return "PromotionDetailsViewControllerId" }
}

extension PromotionDetailsViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case ShowSellerProfile = "ShowSellerProfile"

        var kind: SegueKind? {
            switch (self) {
            case ShowSellerProfile:
                return SegueKind(rawValue: "show")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case ShowSellerProfile:
                return UserProfileViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - ProductInventoryViewController
extension UIStoryboardSegue {
    func selection() -> ProductInventoryViewController.Segue? {
        if let identifier = self.identifier {
            return ProductInventoryViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension ProductInventoryViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case ShowProductDetails = "ShowProductDetails"

        var kind: SegueKind? {
            switch (self) {
            case ShowProductDetails:
                return SegueKind(rawValue: "show")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case ShowProductDetails:
                return ProductDetailsViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - PostViewController
extension UIStoryboardSegue {
    func selection() -> PostViewController.Segue? {
        if let identifier = self.identifier {
            return PostViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension PostViewController: IdentifiableProtocol { 
    var identifier: String? { return "PostViewController" }
    static var identifier: String? { return "PostViewController" }
}

extension PostViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case ShowUserProfile = "ShowUserProfile"

        var kind: SegueKind? {
            switch (self) {
            case ShowUserProfile:
                return SegueKind(rawValue: "show")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case ShowUserProfile:
                return UserProfileViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - BrowseMainGridController

//MARK: - BrowseViewController
extension UIStoryboardSegue {
    func selection() -> BrowseViewController.Segue? {
        if let identifier = self.identifier {
            return BrowseViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension BrowseViewController: IdentifiableProtocol { 
    var identifier: String? { return "MapViewController" }
    static var identifier: String? { return "MapViewController" }
}

extension BrowseViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case ShowProductDetails = "ShowProductDetails"
        case ShowEventDetails = "ShowEventDetails"
        case ShowPromotionDetails = "ShowPromotionDetails"
        case ShowPost = "ShowPost"

        var kind: SegueKind? {
            switch (self) {
            case ShowProductDetails:
                return SegueKind(rawValue: "show")
            case ShowEventDetails:
                return SegueKind(rawValue: "show")
            case ShowPromotionDetails:
                return SegueKind(rawValue: "show")
            case ShowPost:
                return SegueKind(rawValue: "show")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case ShowProductDetails:
                return ProductDetailsViewController.self
            case ShowEventDetails:
                return EventDetailsViewController.self
            case ShowPromotionDetails:
                return PromotionDetailsViewController.self
            case ShowPost:
                return PostViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - PeopleViewController
extension UIStoryboardSegue {
    func selection() -> PeopleViewController.Segue? {
        if let identifier = self.identifier {
            return PeopleViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension PeopleViewController: IdentifiableProtocol { 
    var identifier: String? { return "PeopleViewController" }
    static var identifier: String? { return "PeopleViewController" }
}

extension PeopleViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case ShowUserProfile = "ShowUserProfile"

        var kind: SegueKind? {
            switch (self) {
            case ShowUserProfile:
                return SegueKind(rawValue: "show")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case ShowUserProfile:
                return UserProfileViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - UserProfileViewController
extension UserProfileViewController: IdentifiableProtocol { 
    var identifier: String? { return "UserProfileViewController" }
    static var identifier: String? { return "UserProfileViewController" }
}


//MARK: - CommunityFeedViewController
extension CommunityFeedViewController: IdentifiableProtocol { 
    var identifier: String? { return "CommunityFeedViewController" }
    static var identifier: String? { return "CommunityFeedViewController" }
}


//MARK: - ChangePasswordViewController
extension ChangePasswordViewController: IdentifiableProtocol { 
    var identifier: String? { return "ChangePasswordController" }
    static var identifier: String? { return "ChangePasswordController" }
}


//MARK: - SettingsViewController
extension UIStoryboardSegue {
    func selection() -> SettingsViewController.Segue? {
        if let identifier = self.identifier {
            return SettingsViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension SettingsViewController: IdentifiableProtocol { 
    var identifier: String? { return "SettingsViewController" }
    static var identifier: String? { return "SettingsViewController" }
}

extension SettingsViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case showChangePassword = "showChangePassword"

        var kind: SegueKind? {
            switch (self) {
            case showChangePassword:
                return SegueKind(rawValue: "show")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case showChangePassword:
                return ChangePasswordViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - CommunityViewController
extension CommunityViewController: IdentifiableProtocol { 
    var identifier: String? { return "CommunityViewController" }
    static var identifier: String? { return "CommunityViewController" }
}


//MARK: - WalletViewController
extension WalletViewController: IdentifiableProtocol { 
    var identifier: String? { return "WalletViewController" }
    static var identifier: String? { return "WalletViewController" }
}


//MARK: - CreateCommunityConversationViewController
extension CreateCommunityConversationViewController: IdentifiableProtocol { 
    var identifier: String? { return "CreateCommunityConversationViewController" }
    static var identifier: String? { return "CreateCommunityConversationViewController" }
}


//MARK: - CreateUserConversationViewController
extension CreateUserConversationViewController: IdentifiableProtocol { 
    var identifier: String? { return "CreateUserConversationViewController" }
    static var identifier: String? { return "CreateUserConversationViewController" }
}


//MARK: - CreateConversationViewController

//MARK: - LoginSignupViewController
extension UIStoryboardSegue {
    func selection() -> LoginSignupViewController.Segue? {
        if let identifier = self.identifier {
            return LoginSignupViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension LoginSignupViewController: IdentifiableProtocol { 
    var identifier: String? { return "LoginSignUpViewController" }
    static var identifier: String? { return "LoginSignUpViewController" }
}

extension LoginSignupViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case SignUpSegueId = "SignUpSegueId"
        case LoginSegueId = "LoginSegueId"

        var kind: SegueKind? {
            switch (self) {
            case SignUpSegueId:
                return SegueKind(rawValue: "show")
            case LoginSegueId:
                return SegueKind(rawValue: "show")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case SignUpSegueId:
                return RegisterViewController.self
            case LoginSegueId:
                return LoginViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - RegisterViewController
extension UIStoryboardSegue {
    func selection() -> RegisterViewController.Segue? {
        if let identifier = self.identifier {
            return RegisterViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension RegisterViewController: IdentifiableProtocol { 
    var identifier: String? { return "RegisterViewController" }
    static var identifier: String? { return "RegisterViewController" }
}

extension RegisterViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case SignUpSegue = "SignUpSegue"

        var kind: SegueKind? {
            switch (self) {
            case SignUpSegue:
                return SegueKind(rawValue: "show")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case SignUpSegue:
                return RegisterInfoViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - RecoverPasswordViewController
extension RecoverPasswordViewController: IdentifiableProtocol { 
    var identifier: String? { return "RecoverPasswordViewController" }
    static var identifier: String? { return "RecoverPasswordViewController" }
}


//MARK: - LoginViewController
extension UIStoryboardSegue {
    func selection() -> LoginViewController.Segue? {
        if let identifier = self.identifier {
            return LoginViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension LoginViewController: IdentifiableProtocol { 
    var identifier: String? { return "LoginViewController" }
    static var identifier: String? { return "LoginViewController" }
}

extension LoginViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case ForgotPasswordSegueId = "ForgotPasswordSegueId"

        var kind: SegueKind? {
            switch (self) {
            case ForgotPasswordSegueId:
                return SegueKind(rawValue: "show")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case ForgotPasswordSegueId:
                return RecoverPasswordViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - RegisterInfoViewController
extension RegisterInfoViewController: IdentifiableProtocol { 
    var identifier: String? { return "RegisterInfoViewController" }
    static var identifier: String? { return "RegisterInfoViewController" }
}


//MARK: - AddProductViewController
extension UIStoryboardSegue {
    func selection() -> AddProductViewController.Segue? {
        if let identifier = self.identifier {
            return AddProductViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension AddProductViewController: IdentifiableProtocol { 
    var identifier: String? { return "AddProductViewController" }
    static var identifier: String? { return "AddProductViewController" }
}

extension AddProductViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case Close = "Close"

        var kind: SegueKind? {
            switch (self) {
            case Close:
                return SegueKind(rawValue: "unwind")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            default:
                assertionFailure("Unknown destination")
                return nil
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - AddPostViewController
extension AddPostViewController: IdentifiableProtocol { 
    var identifier: String? { return "AddPostViewController" }
    static var identifier: String? { return "AddPostViewController" }
}


//MARK: - AddCommunityViewController
extension UIStoryboardSegue {
    func selection() -> AddCommunityViewController.Segue? {
        if let identifier = self.identifier {
            return AddCommunityViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension AddCommunityViewController: IdentifiableProtocol { 
    var identifier: String? { return "AddCommunityViewController" }
    static var identifier: String? { return "AddCommunityViewController" }
}

extension AddCommunityViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case Close = "Close"

        var kind: SegueKind? {
            switch (self) {
            case Close:
                return SegueKind(rawValue: "unwind")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            default:
                assertionFailure("Unknown destination")
                return nil
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - EditCommunityViewController
extension UIStoryboardSegue {
    func selection() -> EditCommunityViewController.Segue? {
        if let identifier = self.identifier {
            return EditCommunityViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension EditCommunityViewController: IdentifiableProtocol { 
    var identifier: String? { return "EditCommunityViewController" }
    static var identifier: String? { return "EditCommunityViewController" }
}

extension EditCommunityViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case Close = "Close"

        var kind: SegueKind? {
            switch (self) {
            case Close:
                return SegueKind(rawValue: "unwind")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            default:
                assertionFailure("Unknown destination")
                return nil
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - EditProfileViewController
extension UIStoryboardSegue {
    func selection() -> EditProfileViewController.Segue? {
        if let identifier = self.identifier {
            return EditProfileViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension EditProfileViewController: IdentifiableProtocol { 
    var identifier: String? { return "EditProfileViewController" }
    static var identifier: String? { return "EditProfileViewController" }
}

extension EditProfileViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case Close = "Close"

        var kind: SegueKind? {
            switch (self) {
            case Close:
                return SegueKind(rawValue: "unwind")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            default:
                assertionFailure("Unknown destination")
                return nil
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - PostToContainerViewController
extension PostToContainerViewController: IdentifiableProtocol { 
    var identifier: String? { return "PostToContainerViewControllerId" }
    static var identifier: String? { return "PostToContainerViewControllerId" }
}


//MARK: - AddPromotionViewController
extension UIStoryboardSegue {
    func selection() -> AddPromotionViewController.Segue? {
        if let identifier = self.identifier {
            return AddPromotionViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension AddPromotionViewController: IdentifiableProtocol { 
    var identifier: String? { return "AddPromotionViewController" }
    static var identifier: String? { return "AddPromotionViewController" }
}

extension AddPromotionViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case Close = "Close"

        var kind: SegueKind? {
            switch (self) {
            case Close:
                return SegueKind(rawValue: "unwind")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            default:
                assertionFailure("Unknown destination")
                return nil
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - AddEventViewController
extension UIStoryboardSegue {
    func selection() -> AddEventViewController.Segue? {
        if let identifier = self.identifier {
            return AddEventViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension AddEventViewController: IdentifiableProtocol { 
    var identifier: String? { return "AddEventViewController" }
    static var identifier: String? { return "AddEventViewController" }
}

extension AddEventViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case Close = "Close"

        var kind: SegueKind? {
            switch (self) {
            case Close:
                return SegueKind(rawValue: "unwind")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            default:
                assertionFailure("Unknown destination")
                return nil
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - OnboardingNavigationController

//MARK: - PhoneNumberViewController
extension UIStoryboardSegue {
    func selection() -> PhoneNumberViewController.Segue? {
        if let identifier = self.identifier {
            return PhoneNumberViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension PhoneNumberViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case PhoneNumberSegueId = "PhoneNumberSegueId"

        var kind: SegueKind? {
            switch (self) {
            case PhoneNumberSegueId:
                return SegueKind(rawValue: "show")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case PhoneNumberSegueId:
                return PhoneVerificationViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - PhoneVerificationViewController
extension UIStoryboardSegue {
    func selection() -> PhoneVerificationViewController.Segue? {
        if let identifier = self.identifier {
            return PhoneVerificationViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension PhoneVerificationViewController: IdentifiableProtocol { 
    var identifier: String? { return "PhoneVerificationController" }
    static var identifier: String? { return "PhoneVerificationController" }
}

extension PhoneVerificationViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case ProfileSegueId = "ProfileSegueId"

        var kind: SegueKind? {
            switch (self) {
            case ProfileSegueId:
                return SegueKind(rawValue: "show")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case ProfileSegueId:
                return EditProfileViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - EditProfileViewController

//MARK: - MembershipPlansViewController
extension MembershipPlansViewController: IdentifiableProtocol { 
    var identifier: String? { return "MembershipPlansViewController" }
    static var identifier: String? { return "MembershipPlansViewController" }
}


//MARK: - PlansViewController
extension PlansViewController: IdentifiableProtocol { 
    var identifier: String? { return "PlansViewController" }
    static var identifier: String? { return "PlansViewController" }
}


//MARK: - SelectMembershipPlansViewController
extension SelectMembershipPlansViewController: IdentifiableProtocol { 
    var identifier: String? { return "SelectMembershipPlansViewController" }
    static var identifier: String? { return "SelectMembershipPlansViewController" }
}


//MARK: - OnboardingNavigationController
extension OnboardingNavigationController: IdentifiableProtocol { 
    var identifier: String? { return "PhoneNumberNavigationController" }
    static var identifier: String? { return "PhoneNumberNavigationController" }
}


//MARK: - CallAmbulanceViewController
extension UIStoryboardSegue {
    func selection() -> CallAmbulanceViewController.Segue? {
        if let identifier = self.identifier {
            return CallAmbulanceViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension CallAmbulanceViewController: IdentifiableProtocol { 
    var identifier: String? { return "CallAmbulanceViewController" }
    static var identifier: String? { return "CallAmbulanceViewController" }
}

extension CallAmbulanceViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case AmbulanceRequestedSegueId = "AmbulanceRequestedSegueId"

        var kind: SegueKind? {
            switch (self) {
            case AmbulanceRequestedSegueId:
                return SegueKind(rawValue: "show")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case AmbulanceRequestedSegueId:
                return AmbulanceRequestedViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - AmbulanceSentViewController
extension AmbulanceSentViewController: IdentifiableProtocol { 
    var identifier: String? { return "AmbulanceSentViewControllerId" }
    static var identifier: String? { return "AmbulanceSentViewControllerId" }
}


//MARK: - DonateViewController
extension UIStoryboardSegue {
    func selection() -> DonateViewController.Segue? {
        if let identifier = self.identifier {
            return DonateViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension DonateViewController: IdentifiableProtocol { 
    var identifier: String? { return "DonateViewController" }
    static var identifier: String? { return "DonateViewController" }
}

extension DonateViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case ShowBraintree = "ShowBraintree"
        case PaymentCompleted = "PaymentCompleted"

        var kind: SegueKind? {
            switch (self) {
            case ShowBraintree:
                return SegueKind(rawValue: "show")
            case PaymentCompleted:
                return SegueKind(rawValue: "show")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case ShowBraintree:
                return BraintreePaymentViewController.self
            case PaymentCompleted:
                return UINavigationController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - SelectPaymentMethodController
extension SelectPaymentMethodController: IdentifiableProtocol { 
    var identifier: String? { return "SelectPaymentMethodController" }
    static var identifier: String? { return "SelectPaymentMethodController" }
}


//MARK: - PaymentViewController
extension PaymentViewController: IdentifiableProtocol { 
    var identifier: String? { return "PaymentViewControllerId" }
    static var identifier: String? { return "PaymentViewControllerId" }
}


//MARK: - BraintreePaymentViewController
extension BraintreePaymentViewController: IdentifiableProtocol { 
    var identifier: String? { return "BraintreePaymentViewController" }
    static var identifier: String? { return "BraintreePaymentViewController" }
}


//MARK: - DonateNotificationViewController
extension DonateNotificationViewController: IdentifiableProtocol { 
    var identifier: String? { return "DonateNotificationViewController" }
    static var identifier: String? { return "DonateNotificationViewController" }
}


//MARK: - AmbulanceRequestedViewController
extension UIStoryboardSegue {
    func selection() -> AmbulanceRequestedViewController.Segue? {
        if let identifier = self.identifier {
            return AmbulanceRequestedViewController.Segue(rawValue: identifier)
        }
        return nil
    }
}

extension AmbulanceRequestedViewController: IdentifiableProtocol { 
    var identifier: String? { return "AmbulanceRequestedViewControllerId" }
    static var identifier: String? { return "AmbulanceRequestedViewControllerId" }
}

extension AmbulanceRequestedViewController { 

    enum Segue: String, CustomStringConvertible, SegueProtocol {
        case AmbulanceSentSegueId = "AmbulanceSentSegueId"

        var kind: SegueKind? {
            switch (self) {
            case AmbulanceSentSegueId:
                return SegueKind(rawValue: "show")
            }
        }

        var destination: UIViewController.Type? {
            switch (self) {
            case AmbulanceSentSegueId:
                return AmbulanceSentViewController.self
            }
        }

        var identifier: String? { return self.description } 
        var description: String { return self.rawValue }
    }

}

//MARK: - PaymentCompletedViewController
extension PaymentCompletedViewController: IdentifiableProtocol { 
    var identifier: String? { return "PaymentCompletedViewController" }
    static var identifier: String? { return "PaymentCompletedViewController" }
}

